---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development-bgd
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: development
        requeueAfterSeconds: 30
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-development-bgd'
    spec:
      destination:
        server: '{{server}}'
      project: development-appproject
      revisionHistoryLimit: 5
      source:
        path: 'workloads/bgd/overlays/{{name}}'
        repoURL: 'https://github.com/danifernandezs/ACM-ArgoCD-AppSetGenerators.git'
        targetRevision: main
      syncPolicy: {}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preproduction-bgd
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: preproduction
        requeueAfterSeconds: 30
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-preproduction-bgd'
    spec:
      destination:
        server: '{{server}}'
      project: preproduction-appproject
      revisionHistoryLimit: 5
      source:
        path: 'workloads/bgd/overlays/{{name}}'
        repoURL: 'https://github.com/danifernandezs/ACM-ArgoCD-AppSetGenerators.git'
        targetRevision: main
      syncPolicy: {}
